[package]
name = "pulsevm_proc_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1.0.13", features = ["full"] }
pulsevm_name = { path = "../pulsevm_name" }

[lib]
proc-macro = true