[package]
name = "pulsevm_arena"
version = "0.1.0"
edition = "2024"

[dependencies]
zerocopy = { version = "0.8", features = ["derive"] }

[dev-dependencies]
zerocopy = { version = "0.8", features = ["derive"] }
tempfile = "3"
criterion = { version = "0.5" }

[[bench]]
name = "arena"
harness = false
