pub mod abi;
pub mod account;
pub mod apply_context;
pub mod asset;
pub mod authority;
pub mod authority_checker;
pub mod authorization_manager;
pub mod block;
pub mod config;
pub mod controller;
mod genesis;
pub mod id;
pub mod mempool;
pub mod name;
pub mod pulse_contract;
pub mod resource;
pub mod resource_limits;
pub mod secp256k1;
pub mod state_history;
pub mod transaction;
pub mod transaction_context;
pub mod utils;
pub mod wasm_runtime;
mod webassembly;

use crate::chain::name::Name;
use pulsevm_proc_macros::name;

pub const PULSE_NAME: u64 = name!("pulse");
pub const OWNER_NAME: u64 = name!("owner");
pub const ACTIVE_NAME: u64 = name!("active");
pub const ANY_NAME: u64 = name!("pulse.any");
pub const CODE_NAME: u64 = name!("pulse.code");
