mod node_config;
pub use node_config::NodeConfig;

use crate::name::Name;
use pulsevm_constants::PERCENT_100;
use pulsevm_name_macro::name;

pub const PLUGIN_VERSION: u32 = 43;
pub const VERSION: &str = "v0.0.1";

/// Metering points per microsecond of reference CPU time. This is the physical
/// anchor for the whole CPU model: the operator table plus the host-intrinsic
/// table in `webassembly::cost` both bill in these points, and one point is
/// ~1/38000 µs on reference hardware (measured by the `estimate_intrinsic_costs`
/// tool; see `docs/intrinsic-cost-model.md`).
///
/// It's the bridge between a wall-clock intuition and a point budget: a CPU
/// limit meant to buy `n` microseconds of work is `n * POINTS_PER_US` points.
/// The genesis `max_block_cpu_usage` / `max_transaction_cpu_usage` are chosen
/// this way. Note `cpu_usage_us` in the receipt is `u32`, so per-transaction
/// billed points must stay below ~4.29e9 (~113 ms of reference compute).
///
/// Changing this rescales billed CPU, so it's a consensus value.
pub const POINTS_PER_US: u64 = 38_000;

/// Metering budget for an implicit system transaction (`cpu_limit == -1`, e.g.
/// `onblock`). These are generated by the chain itself, not submitted by users,
/// so they get a budget far above any normal transaction — but a *finite* one, so
/// a buggy system contract can't spin a node forever.
///
/// Capped at the `u32` `cpu_usage_us` receipt ceiling: billed points are recorded
/// in that field (see `POINTS_PER_US` above and `add_cpu_usage`), so a budget
/// above `u32::MAX` is unreachable — a tx billed past the ceiling fails with a
/// CPU-usage overflow rather than running to the larger budget. `u32::MAX` points
/// is ~113 ms of reference compute, still ~4x a full `max_transaction_cpu_usage`
/// of 1e9 and far above any real system action, while remaining a hard stop that
/// bounds a runaway loop until a proper native-code checktime deadline exists.
pub const IMPLICIT_TX_CPU_BUDGET: u64 = u32::MAX as u64;

// Names
pub const NEWACCOUNT_NAME: Name = Name::new(name!("newaccount"));
pub const SETCODE_NAME: Name = Name::new(name!("setcode"));
pub const SETABI_NAME: Name = Name::new(name!("setabi"));
pub const UPDATEAUTH_NAME: Name = Name::new(name!("updateauth"));
pub const DELETEAUTH_NAME: Name = Name::new(name!("deleteauth"));
pub const LINKAUTH_NAME: Name = Name::new(name!("linkauth"));
pub const UNLINKAUTH_NAME: Name = Name::new(name!("unlinkauth"));
pub const ONERROR_NAME: Name = Name::new(name!("onerror"));
pub const ONBLOCK_NAME: Name = Name::new(name!("onblock"));

pub const fn eos_percent(value: u64, percentage: u32) -> u64 {
    (value * percentage as u64) / PERCENT_100
}

#[cfg(test)]
mod tests {
    use super::*;

    // Billed points land in the u32 `cpu_usage_us` receipt field, so a budget
    // above u32::MAX is unreachable: a transaction billed past the ceiling fails
    // with a CPU-usage overflow instead of running to the larger budget. Keep the
    // implicit-tx budget within what the receipt can actually record.
    #[test]
    fn implicit_tx_budget_fits_the_cpu_usage_receipt() {
        assert!(IMPLICIT_TX_CPU_BUDGET <= u32::MAX as u64);
    }
}
